### ISSUE TITLE
Enable addition/removal of multiple tokens in IE

### ISSUE THREAD

**Issue by Alhadis** [Alhadis/DOMTokenList-Polyfill#5]
IE11 (and probably IE10, too) [has a bug](https://connect.microsoft.com/IE/Feedback/Details/920755) where multiple tokens can't be added or removed at once.

```
element.classList.add("coloured", "green");
console.log( element.className ); /** Modern browsers: "coloured green" */
console.log( element.className);  /** IE11: "coloured" */
```

**Comment by ganlanyuan** [comment]
I tested in IE 10 and 11, this issue still comes out.
I used your latest version (https://raw.githubusercontent.com/Alhadis/DOMTokenList/master/min/token-list.js).

```
var firstEl = document.querySelector('.first');
firstEl.classList.add('bold', 'italic', 'red'); // only bold is added
```

Anything wrong?

**Comment by Alhadis** [comment]
Hi @ganlanyuan,

I'll look into this immediately, but can you check you're not using conditional comments to load the file? Support for conditional comments was dropped in IE 10+, so something like `<!--[if IE]>` isn't going to work.

**EDIT:** Just to confirm, I can't reproduce this in IE10.  It should be working for you too. Is the polyfill being loaded _before_ you're adding multiple classes? It needs to load first (this includes asynchronous or deferred loading; that is, with a `<script>` tag's `async` or `defer` attributes).

**Comment by ganlanyuan** [comment]
Hi, I didn't use conditional comment actually. I included it right before the close </body> tag.

**Comment by Alhadis** [comment]
Are you using any other polyfills?

[See my message here](https://github.com/Alhadis/DOMTokenList/issues/6#issuecomment-194655683). You might need to drop a few unneeded ones in case they're causing conflicts. The polyfill _should_ play nicely with others, but I haven't tested that for myself. I didn't expect users would need to load the same polyfill more than once.

**Comment by ganlanyuan** [comment]
Here is my markup:

``` html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>classList: add, remove, toggle</title>

  <link rel="stylesheet" href="css/classlist.css">
  <script type="text/javascript" src="https://raw.githubusercontent.com/Alhadis/DOMTokenList/master/src/token-list.js"></script>
</head>
<body>
  <h3>Add: bold, red, underline, heading</h3>
  <p id="addClasses">Placeat eveniet, ea totam neque ab error facere nam maxime dolores molestiae tempore pariatur, consectetur fuga! Non deserunt, incidunt magnam.</p>
  <h3>Remove:bold, red, underline, italic, heading</h3>
  <p id="removeClasses" class="red bold italic underline heading">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis dolorem reiciendis eveniet suscipit? Reiciendis, molestiae unde, officia quisquam sunt corporis.</p>
  <h3>Toggle: remove italic, add red</h3>
  <p id="toggleClass" class="italic">Voluptatem dolor ratione sint nostrum dolore laudantium alias esse dolorum veniam quisquam, recusandae velit, omnis? Temporibus, porro. Repellat ipsa, adipisci.</p>

  <script type="text/javascript">
    var 
        ad = document.querySelector('#addClasses'),
        rm = document.querySelector('#removeClasses'),
        tg = document.querySelector('#toggleClass');

    ad.classList.add('bold', 'red', 'underline', 'heading');
    rm.classList.remove('bold', 'red', 'underline', 'italic', 'heading');
    tg.classList.toggle('red', true);
    tg.classList.toggle('italic', false);
  </script>
</body>
</html>
```

and css:

``` css
body { margin: 0; font-family: Arial, "Helvetica Neue", Helvetica, sans-serif; }
ul { margin: 0; padding: 0; }
li { list-style: none; }
a { color: inherit; text-decoration: none; }

h3 {
  margin: 60px 0 0;
  font-size: 20px;
}
h3, p { padding: 0 calc(50% - 450px); }
p { margin: 10px 0; }
.heading { font-size: 40px; }
.bold { font-weight: bold; }
.italic { font-style: italic; }
.red { color: red; }
.underline { text-decoration: underline; }
```

Screenshot on IE 10 & 11:
![ie10](https://cloud.githubusercontent.com/assets/4998811/13774263/79dc487a-ea74-11e5-8382-c4406479ddb5.png)
![ie11](https://cloud.githubusercontent.com/assets/4998811/13774262/79d9794c-ea74-11e5-93b3-18e4283ec4e0.png)

Could you check? 
Thanks
